### ISSUE TITLE
Not work status bar coloring after first set.

### ISSUE THREAD

**Issue by Se7Touch** [CreatureSurvive/Fabric-Issues#20]
...

**Comment by CreatureSurvive** [comment]
I need more information so I can reproduce the issue and fix it. … doesn't explain the issue your having. 

- Did the statusbar color change when you first installed and now it's stuck on the same color?
- Is it not coloring at all?
- Did you change any of the statusbar color settings?
- Do you have any other tweaks that modify the statusbar?

**Comment by Se7Touch** [comment]
1. Yes, im first install tweak and middle color automaticly set green and statusbar color same a middle bar. After im changing middle bar manuel color but not change a status bar same middle bar and now green stuck.

2. Yes status bar is green color stuck.

3. Yes i try top and bottom bar colors for status bar but not change.

4. Only xeon tweak and i use status bar a littlexs modern statusbar

**Comment by CreatureSurvive** [comment]
Thanks for the info, I'm looking into it right now.

**Comment by CreatureSurvive** [comment]
Actually I found the issue already, I'll release a fix for this shortly. Thanks for bringing this to my attention

**Comment by Se7Touch** [comment]
Thanx for help :) waiting...
