### ISSUE TITLE
Photos app freezes

### ISSUE THREAD

**Issue by kasti0** [CreatureSurvive/Fabric-Issues#22]
With the newest update the photos app freezes when pressing the button to set a new wallpaper

**Comment by ghost** [comment]
I can confirm this

**Comment by CreatureSurvive** [comment]
@kasti0 @Marvix1711 I was able to reproduce this on my device, I'll see if I can get this fixed today. Thanks for letting me know. 

Also it looks like it's not completely freezing, it does load but it takes a while. Either way, I'm working on it.

**Comment by CreatureSurvive** [comment]
Just released v1.5.1 fixing this issue.

**Comment by ghost** [comment]
Yes it’s fixed thanks👍🏻
