### ISSUE TITLE
Current weather only shows as 0 degrees

### ISSUE THREAD

**Issue by Galbraithm** [CreatureSurvive/Fabric-Issues#3]
Can’t seem to find any way to make it update.
![7E73A7BC-E0BD-42AB-B1A5-61A3331FE3A4](https://user-images.githubusercontent.com/41162110/58766202-cffbc000-8549-11e9-9fba-3399c7c81113.png)

**Comment by CreatureSurvive** [comment]
Closing this issue since the original poster has not responded with more information after 2 weeks.
