### ISSUE TITLE
Conflict with Lisa after update to v1.3.0

### ISSUE THREAD

**Issue by kasti0** [CreatureSurvive/Fabric-Issues#6]
I got stuck in the preferences of fabric, just could scroll up and down, so I had to force restart my iPhone.
Afterwards I was not able to load tweaks anymore, not with load tweaks enabled in unc0ver, not with an manual terminal command and not with iCleaner. Had to downgrade to 1.2.5 to load my tweaks again.

**Comment by CreatureSurvive** [comment]
I'm honestly not sure if I fixed this or if the conflict never had anything to do with Fabric. Either way, I've tested v1.4.4 with Lisa and all is working well. I'm going to close this now.
